defaultPlacement: end
fieldLayouts:
  f4c858c9-307a-4cff-9f34-412de984cc39:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: blogCategories
name: 'Blog Categories'
siteSettings:
  4d8ac26f-0eed-4e84-8f0f-fb59450142e3: # English
    hasUrls: false
    template: null
    uriFormat: null
  8ada0e08-6502-434a-b7ff-c252b73ca0df: # German
    hasUrls: false
    template: null
    uriFormat: null
  f5399107-84c7-4af5-8764-8c333d1b9ebc: # Dutch
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 4641dbd1-76ee-44b0-ab32-bb5f902609b0
