defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  4d8ac26f-0eed-4e84-8f0f-fb59450142e3: # $SITE_NAME_EN
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
  8ada0e08-6502-434a-b7ff-c252b73ca0df: # $SITE_NAME_DE
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
  f5399107-84c7-4af5-8764-8c333d1b9ebc: # $SITE_NAME_NL
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
